CREATE TABLE IF NOT EXISTS auth_verification_code (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  target VARCHAR(128) NOT NULL,
  channel VARCHAR(20) NOT NULL,
  code VARCHAR(20) NOT NULL,
  expire_time TIMESTAMP NOT NULL,
  consumed_time TIMESTAMP NULL,
  send_count INT DEFAULT 0,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
