spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://${DB_HOST:24.199.77.196}:${DB_PORT:3306}/${DB_NAME:lightmark}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USER:se}
    password: ${DB_PASSWORD:sebuaa}
  sql:
    init:
      mode: never

server:
  port: ${SERVER_PORT:8080}

timemark:
